phrase:
  project_id: a9be9367c4e81aef6182d66be220b5d3
  push:
    sources:
    - file: ./source-locale/main/json-files/sample-json.json
      params:
        file_format: simple_json
        locale_id: en
        update_translations: true
    - file: ./source-locale/main/json-files/test-germanTM.json
      params:
        file_format: simple_json
        locale_id: en
        update_translations: true
  pull:
    targets:
    - file: ./translation-files/de/sample-json.json
      params:
        locale_id: de
        file_format: simple_json
    - file: ./translation-files/es/sample-json.json
      params:
        locale_id: es
        file_format: simple_json
    - file: ./translation-files/el/sample-json.json
      params:
        locale_id: el
        file_format: simple_json
    - file: ./source-locale/main/json-files/translations/test-germanTM.json
      params:
        locale_id: de
        file_format: simple_json
    - file: ./source-locale/main/json-files/translations/test-germanTM.json
      params:
        locale_id: es
        file_format: simple_json
    - file: ./source-locale/main/json-files/translations/test-germanTM.json
      params:
        locale_id: el
        file_format: simple_json
